import {test,expect} from '@playwright/test';
const password=process.env.LIFE_OS_TEST_PASSWORD;
test('workout timer survives reload; saved sets produce records; all three grids work on mobile',async({page})=>{
 test.skip(!password,'Requires disposable local database');
 test.setTimeout(120000);
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.goto('/#physical');
 await page.getByLabel('Password',{exact:true}).fill(password!);
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page.locator('main h1')).toHaveText('Physical goals');
 const token=await page.evaluate(()=>localStorage.getItem('life-os-token'));
 const headers={Authorization:'Bearer '+token};
 if(new URL(page.url()).hostname!=='127.0.0.1')throw new Error('Local test only');
 for(const w of await (await page.request.get('/api/data/workouts',{headers})).json())if(w.title==='Verification workout')await page.request.delete('/api/data/workouts/'+w.id,{headers});
 await page.reload();
 await page.getByRole('button',{name:'Workouts',exact:true}).click();
 await page.getByLabel('Session name').fill('Verification workout');
 await page.getByRole('button',{name:'Start workout',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Workout in progress'})).toBeVisible();
 await page.reload();
 await page.getByRole('button',{name:'Workouts',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Workout in progress'})).toBeVisible();
 await page.getByRole('button',{name:'Add set',exact:true}).click();
 const dialog=page.getByRole('dialog');
 await dialog.getByRole('combobox',{name:/^Exercise/}).selectOption({label:'Squat'});
 await dialog.getByLabel('Reps',{exact:true}).fill('8');
 await dialog.getByLabel('Weight Kg').fill('40');
 await dialog.getByRole('button',{name:'Save',exact:true}).click();
 await expect(dialog).toHaveCount(0);
 await expect(page.getByText('8 reps × 40 kg',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Finish workout',exact:true}).click();
 await expect(page.getByRole('button',{name:'Start workout',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Personal records',exact:true}).click();
 await expect(page.locator('.pr-headline strong')).toHaveText('40 kg');
 await expect(page.locator('.rep-records')).toContainText('8 reps');
 await page.getByRole('button',{name:'Workouts',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 const grid=page.locator('.activity-panel');
 await expect(grid).toContainText('1 active day');
 const selected=grid.locator('[aria-pressed="true"]');
 await selected.focus();await selected.press('ArrowUp');
 await expect(grid.locator('.activity-detail')).toContainText('Nothing logged');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'/tmp/life-os-training-mobile.png',fullPage:true,animations:'disabled'});
 await page.setViewportSize({width:1440,height:1100});
 await page.screenshot({path:'/tmp/life-os-training-desktop.png',fullPage:true,animations:'disabled'});
 for(const [route,heading] of [['academics','Study activity'],['dsa','DSA activity']]){
   await page.goto('/#'+route);
   await expect(page.getByRole('heading',{name:heading,exact:true})).toBeVisible();
   await expect(page.locator('.activity-grid button').first()).toBeAttached();
   await page.getByRole('button',{name:`Previous year for ${heading}`}).click();
   await expect(page.locator('.activity-year strong')).toHaveText(String(new Date().getFullYear()-1));
 }
});
